server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://ibrahimsahinaws:elif.NUR17@kahve.ccifx0r.mongodb.net/kahve?appName=kahve
  jackson:
    mapper:
      accept-case-insensitive-enums: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:Dt+wSXLLEgZ3uND0dIT5EFWVP9Px6+5jZk+IRc0QwHOiZi2c3vtmL1JFvlbD9iMwPHu/s0w2xE1NkC183EGVXw==}
    issuer: kahve
    access-token-minutes: 360